# Generated by Django 3.0.8 on 2020-08-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0003_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
