# Generated by Django 3.0.8 on 2020-07-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0003_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='user',
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dropshop.Product'),
            preserve_default=False,
        ),
    ]
