# Generated by Django 3.0.8 on 2020-09-04 23:04

from django.db import migrations, models
import django.db.models.deletion
import dropshop.email.models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0005_auto_20200902_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=dropshop.email.models.get_expiration_date)),
                ('confirmation_code', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropshop.User')),
            ],
        ),
    ]
