# Generated by Django 3.0.8 on 2020-09-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0006_forgotpasswordemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='notification_period',
            field=models.DurationField(null=True),
        ),
    ]
