# Generated by Django 3.0.8 on 2020-09-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0007_auto_20200910_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notification_period',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
