# Generated by Django 3.0.8 on 2020-09-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0008_auto_20200911_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(blank=True, default='$', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
