# Generated by Django 3.0.8 on 2020-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0010_remove_confirmationemail_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_code',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
