# Generated by Django 3.0.8 on 2020-09-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0011_user_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_code',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
