# Generated by Django 3.0.8 on 2020-09-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropshop', '0012_auto_20200924_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_code',
        ),
    ]
