"""
Django settings for dropshop project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import timedelta

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wo9+*po&j5xwh&n9*o^2r=m+3lg*(^_z=fe@k9b#&sy(sv+cj*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
API_VERSION = 1

ALLOWED_HOSTS = ['*']

ROOT_APP = 'dropshop'
# Application definition

INSTALLED_APPS = [
    '{}.prepatch'.format(ROOT_APP),
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'webpack_loader',
    "post_office",
    ROOT_APP,
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    '{}.accounts.middleware.AuthenticationMiddleware'.format(ROOT_APP),
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    '{}.errors.HandleExceptionMiddleware'.format(ROOT_APP),
]

ROOT_URLCONF = 'router'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, ROOT_APP, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {}
MIGRATION_MODULES = {
    'auth': '{}.accounts.auth'.format(ROOT_APP),
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        '{}.accounts.authentication.SessionAuthentication'.format(ROOT_APP),
    ],
    'EXCEPTION_HANDLER': '{}.errors.exception_handler'.format(ROOT_APP),
    'UNAUTHENTICATED_USER': None
}

# Authentication

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=200),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=200),
}

AUTH_USER_MODEL = '{}.User'.format(ROOT_APP)
AUTHENTICATION_BACKENDS = [
    '{}.accounts.backends.ModelBackend'.format(ROOT_APP)
]
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/assets/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, ROOT_APP, 'static'),
)

for static_dir in (STATIC_ROOT, *STATICFILES_DIRS):
    os.makedirs(static_dir, exist_ok=True)

# WEBPACK
WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'dist/',  # must end with slash
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map']
    }
}

# Emails
EMAIL_BACKEND = 'post_office.EmailBackend'

# celery
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_ALWAYS_EAGER = False
CELERY_TASK_ALWAYS_EAGER = False

# cors
CORS_ALLOW_ALL_ORIGINS = True

# proxy
SCRAPER_PROXY_URL = ''
SCRAPER_PROXY_USERNAME = ''
SCRAPER_PROXY_PASSWORD = ''
